### ISSUE TITLE
the reason behind burst size always > 1?

### ISSUE THREAD

**Issue by vitkl** [sandberg-lab/txburst#15]
Fantastic work! Maybe I am missing something obvious but what is the reason why burst size is always > 1?
Surely if k_syn=1 (min cutoff) and k_off>1 you will get a burst size < 1 using `burst size = k_syn/k_off`. Would be great if you can point me to an explanation.

**Comment by AntonJMLarsson** [comment]
Hello! 

Thanks for your feedback! The reason why is because it's a part of the filtering in the burstML.py script, I might not have been  clear about that in the methods description, my bad. The thought behind it was that a burst size below 1 would be biologically unfeasible, another consideration is that burst size estimates that low are often noisy. However, one could make the case to include estimates lower than 1 since the sensitivity of the method (i.e. detecting RNA molecules) lowers burst size estimates. It's perfectly reasonable to exclude this filtering step, simply delete line 16 and modify line 18 in the burstML.py script. 

If you look at Sup. Fig. 3 in this follow up paper, [https://doi.org/10.1038/s41594-019-0306-y](https://doi.org/10.1038/s41594-019-0306-y), you can see what kind of genes are filtered away by this step (not only by `burst size > 1` but the other filters too).

Hopes this helps.

**Comment by vitkl** [comment]
Hi Anton!

Thanks for explaining and the additional reference. So, just to make sure I
understand this, you are saying that burst size less than one is
biologically unfeasible because less than one mRNA cannot be transcribed?
If this assumption is correct it may be possible to use this hard
biological limit to quantify the extent of technical effects (sensitivity),
does this make sense?

Also related to the question of cut-offs, I am trying to understand if it
valid to say that the lowly expressed genes (or silent genes) in a specific
cell type have 0 burst size and/or frequency. When looking at the
difference between cell types you do not consider this case, only the genes
for which you can confidently infer both parameters, right?
